practica2/practica2/urls.py
from django.conf.urls import patterns, include, url
from iTeatre.views import *
from django.views.generic import DetailView, ListView, UpdateView 
from iTeatre.forms import *
from iTeatre.models import *
from django.utils import timezone
from rest_framework.urlpatterns import format_suffix_patterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

	url(r'^$', mainpage, name='home'),

#-------------------------------------------------ESCRIPTOR-----------------------------------------------

	# LIST
	url(r'^escriptors$', ListView.as_view(queryset=Escriptor.objects.filter(),context_object_name='contentbody', template_name='llista.html'), name='escriptor_list'),

	# UPDATE
	url(r'^escriptors/(?P<pk>\d+)/edit/$', GenericUpdate.as_view(
	model = Escriptor,
	template_name = 'form.html', 
	form_class = EscriptorForm), 
	name='update_escriptor'),

	# CREATE
	url(r'^escriptors/create/$', GenericCreate.as_view(
	model =  Escriptor,
	template_name = 'form.html',
	form_class = EscriptorForm), 
	name='escriptor_create'),
	
	# DETAIL
	url(r'^escriptors/(?P<pk>\d+)/$',GenericDetail.as_view(
	model = Person,
	template_name = 'dades.html'), 
	name='escriptor_detail'),

	# DELETE
	url(r'^escriptors/(?P<pk>\d+)/delete/$',GenericDelete.as_view(
	model = Escriptor,
	template_name = 'form.html', 
	success_url = '/escriptors'),
	name='escriptor_delete'),

#-------------------------------------------------ACTOR-----------------------------------------------
	
	# LIST
	url(r'^actors$', ListView.as_view(queryset=Actor.objects.filter(),context_object_name='contentbody', template_name='llista.html'), name='Llista actors'),

	# UPDATE
	url(r'^actors/(?P<pk>\d+)/edit/$', GenericUpdate.as_view(
	model = Actor,
	template_name = 'form.html', 
	form_class = ActorForm), 
	name='update_actor'),

	# CREATE
	url(r'^actors/create/$', GenericCreate.as_view(
	model =  Actor,
	template_name = 'form.html',
	form_class = ActorForm), 
	name='actor_create'),
	
	# DETAIL
	url(r'^actors/(?P<pk>\d+)/$',GenericDetail.as_view(
	model = Person,
	template_name = 'dades.html'), 
	name='actor_detail'),

	# DELETE
	url(r'^actors/(?P<pk>\d+)/delete/$',GenericDelete.as_view(
	model = Actor,
	template_name = 'form.html', 
	success_url = '/actors'),
	name='actor_delete'),

#-------------------------------------------------DIRECTOR-----------------------------------------------
	
	# LIST
	url(r'^directors$', ListView.as_view(queryset=Director.objects.filter(),context_object_name='contentbody', template_name='llista.html'), name='Llista directors'),

	# UPDATE
	url(r'^directors/(?P<pk>\d+)/edit/$', GenericUpdate.as_view(
	model = Director,
	template_name = 'form.html', 
	form_class = DirectorForm), 
	name='update_director'),

	# CREATE
	url(r'^directors/create/$', GenericCreate.as_view(
	model =  Director,
	template_name = 'form.html',
	form_class = DirectorForm), 
	name='director_create'),
	
	# DETAIL
	url(r'^directors/(?P<pk>\d+)/$',GenericDetail.as_view(
	model = Person,
	template_name = 'dades.html'), 
	name='director_detail'),

	# DELETE
	url(r'^directors/(?P<pk>\d+)/delete/$',GenericDelete.as_view(
	model = Director,
	template_name = 'form.html', 
	success_url = '/directors'),
	name='director_delete'),

#-------------------------------------------------REPRESENTACIO-----------------------------------------------
	
	# LIST
	url(r'^representacions$', ListView.as_view(queryset=Representacio.objects.filter(),context_object_name='contentbody', template_name='llista.html'), name='Llista representacions'),

	# UPDATE
	url(r'^representacions/(?P<pk>\d+)/edit/$', GenericUpdate.as_view(
	model = Representacio,
	template_name = 'form.html', 
	form_class = RepresentacioForm,
	success_url = '/representacions'), 
	name='update_representacio'),
	
	url(r'^representacions/(?P<pk>\d+)/directors/(?P<pkr2>\d+)/edit/$',GenericUpdate.as_view(
	model = Director,
	template_name = 'form.html'), 
	name='representacio_update2'),

	# CREATE
	url(r'^representacions/create/$', GenericCreate.as_view(
	model =  Representacio,
	template_name = 'form.html',
	form_class = RepresentacioForm,
	success_url = '/representacions'), 
	name='representacio_create'),
	
	# DETAIL
	url(r'^representacions/(?P<pk>\d+)/$',GenericDetail.as_view(
	model = Representacio,
	template_name = 'representacio.html'), 
	name='representacio_detail'),
	
	# DETAIL DIRECTOR
	url(r'^representacions/(?P<pk>\d+)/directors/(?P<pkr2>\d+)/$',GenericDetail.as_view(
	model = Person,
	template_name = 'dades.html'), 
	name='representacio_detail2'),
	# DETAIL ACTORS
	url(r'^representacions/(?P<pk>\d+)/actors/(?P<pkr3>\d+)/$',GenericDetail.as_view(
	model = Person,
	template_name = 'dades.html'), 
	name='representacio_detail'),


	# DELETE
	url(r'^representacions/(?P<pk>\d+)/delete/$',GenericDelete.as_view(
	model = Representacio,
	template_name = 'form.html', 
	success_url = '/representacions'),
	name='representacio_delete'),

#-------------------------------------------------OBRA TEATRE-----------------------------------------------
	
	# LIST
	url(r'^obresTeatre$', ListView.as_view(queryset=Obra_Teatre.objects.filter(),context_object_name='contentbody', template_name='llista.html'), name='Llista obres Teatre'),

	# UPDATE
	url(r'^obresTeatre/(?P<pk>\d+)/edit/$', GenericUpdate.as_view(
	model = Obra_Teatre,
	template_name = 'form.html', 
	form_class = Obra_TeatreForm,
	success_url = '/obresTeatre'), 
	name='update_obraTeatre'),

	url(r'^obresTeatre/(?P<pk>\d+)/escriptors/(?P<pkr2>\d+)/edit/$',GenericUpdate.as_view(
	model = Escriptor,
	template_name = 'form.html'), 
	name='update_obraTeatre'),

	# CREATE nom_Obra
	url(r'^obresTeatre/create/$', GenericCreate.as_view(
	model =  nom_Obra,
	template_name = 'form.html',
	form_class = nom_ObraForm,
	success_url = '/obresTeatre/createObra/'), 
	name='obraTeatre_create'),
	

	# CREATE
	url(r'^obresTeatre/createObra/$', GenericCreate.as_view(
	model =  Obra_Teatre,
	template_name = 'form.html',
	form_class = Obra_TeatreForm,
	success_url = '/obresTeatre'), 
	name='obraTeatre_create2'),

	
	# DETAIL
	url(r'^obresTeatre/(?P<pk>\d+)/$',GenericDetail.as_view(
	model = Obra_Teatre,
	template_name = 'infoObresTeatre.html'), 
	name='obra_Teatre_detail'),

	# DETAIL ESCRIPTOR
	url(r'^obresTeatre/(?P<pk>\d+)/escriptors/(?P<pkr2>\d+)/$',GenericDetail.as_view(
	model = Person,
	template_name = 'dades.html'), 
	name='obra_Teatre_detail'),
	
	# DELETE
	url(r'^obresTeatre/(?P<pk>\d+)/delete/$',GenericDelete.as_view(
	model = Obra_Teatre,
	template_name = 'form.html', 
	success_url = '/obresTeatre'),
	name='obraTeatre_delete'),
		


	# ERROR, in logging
	url(r'^accounts/login/$',error,name='error'),

	url(r'^login/$','django.contrib.auth.views.login'),
	#url(r'^Teatre/', include('Teatre.foo.urls')),

	# Uncomment the admin/doc line below to enable admin documentation:
	#url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	# Uncomment the next line to enable the admin:
	url(r'^admin/', include(admin.site.urls)),
)

#-------------------------------------------------RESTful API-----------------------------------------------

urlpatterns += patterns('',

	url(r'^api/escriptors/$', APIEscriptorList.as_view(), name='escriptor-list'),
	url(r'^api/escriptors/(?P<pk>\d+)/$', APIEscriptorDetail.as_view(), name='escriptor-detail'),

	url(r'^api/actors/$', APIActorList.as_view(), name='actor-list'),
	url(r'^api/actors/(?P<pk>\d+)/$', APIActorDetail.as_view(), name='actor-detail'),

	url(r'^api/directors/$', APIDirectorList.as_view(), name='director-list'),
	url(r'^api/directors/(?P<pk>\d+)/$', APIDirectorDetail.as_view(), name='director-detail'),

	url(r'^api/representacions/$', APIRepresentacioList.as_view(), name='representacio-list'),
	url(r'^api/representacions/(?P<pk>\d+)/$', APIRepresentacioDetail.as_view(), name='representacio-detail'),

	url(r'^api/obresTeatre/$', APIObra_TeatreList.as_view(), name='obra_Teatre-list'),
	url(r'^api/obresTeatre/(?P<pk>\d+)/$', APIObra_TeatreDetail.as_view(), name='obra_Teatre-detail'),

	url(r'^api/nomObra/$', APInom_ObraList.as_view(), name='nom_obra-list'),
	url(r'^api/nomObra/(?P<pk>\d+)/$',APInom_ObraDetail.as_view(), name='nom_obra-detail'),
    
    
)

# Format suffixes
urlpatterns = format_suffix_patterns(urlpatterns, allowed=['api' ,'json', 'xml'])

practica2/iTeatre/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import *
from django.core.urlresolvers import reverse


# Create your models here.


class Person(models.Model):
	nom = models.CharField(max_length=40)
	edat = models.IntegerField()
	sexe = models.CharField(max_length=1)
	localitat = models.CharField(max_length=40)


class Escriptor(Person):
	user = models.ForeignKey(User, blank=True,null=True)	
  

	def __unicode__(self):
		return self.nom

	def get_absolute_url(self):
		return reverse('escriptor_detail',kwargs={'pk':self.pk})

  
class Actor(Person):
	user = models.ForeignKey(User,blank=True,null=True)	
	
	def __unicode__(self):
	        return self.nom

	def get_absolute_url(self):
        	return reverse('actor_detail', kwargs={'pk': self.pk})




class Director(Person):
	user = models.ForeignKey(User,blank=True,null=True)	

	def __unicode__(self):
		return self.nom

	def get_absolute_url(self):
        	return reverse('director_detail', kwargs={'pk': self.pk})




class nom_Obra (models.Model):
	nomObra = models.CharField(null=False,max_length=40)
	user = models.ForeignKey(User,blank=True,null=True)	

	def __unicode__(self):
		return self.nomObra

	def get_absolute_url(self):
        	return reverse('nom_obra_detail', kwargs={'pk': self.pk})
	

class Representacio (models.Model):
	nomRepresentacio = models.CharField(max_length=40)
	nomObra = models.ForeignKey(nom_Obra)
	dataInici = models.DateField()
	dataFi = models.DateField()
	actors = models.ManyToManyField(Actor)
	director = models.ForeignKey(Director)
	user = models.ForeignKey(User,blank=True,null=True)	
	
	

	def __unicode__(self):
		return self.nom
	def get_absolute_url(self):
        	return reverse('representacio_detail', kwargs={'pk1': self.nomObra.pk,'pkr2':self.director.pk,'pkr3':self.actors.pk, 'pk': self.pk})


class Obra_Teatre(models.Model):
	nom = models.ForeignKey(nom_Obra)
	Tipus = models.CharField(max_length=40)
	escriptor = models.ForeignKey(Escriptor)
	representacions = models.ManyToManyField(Representacio)
	user = models.ForeignKey(User,blank=True,null=True)	

	def __unicode__(self):
		return self.nom.nomObra

	def get_absolute_url(self):
        	return reverse('obra_Teatre_detail', kwargs={'pkr1': self.nom.pk,'pkr2':self.escriptor.pk, 'pkr3': self.representacions.pk, 'pk': self.pk})

practica2/iTeatre/forms.py
from django.forms import ModelForm	
from models import *	
  
class EscriptorForm(ModelForm):	
	class Meta:	
		model =	Escriptor
		exclude = ('user')	

class ActorForm(ModelForm):	
	class Meta:	
		model =	Actor
		exclude = ('user')	

class DirectorForm(ModelForm):	
	class Meta:	
		model =	Director
		exclude = ('user')	


class RepresentacioForm(ModelForm):	
	class Meta:	
		model =	Representacio
		exclude = ('user')
class Obra_TeatreForm(ModelForm):	
	class Meta:	
		model =	Obra_Teatre
		exclude = ('user')

class nom_ObraForm(ModelForm):	
	class Meta:	
		model =	nom_Obra
		exclude = ('user')
	
  

practica2/iTeatre/views.py
#-*- coding: utf-8 -*-
from django.core.urlresolvers import reverse
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView
from django.views.generic.edit import CreateView
from django.template import Context
from django.template.loader import get_template
from django.contrib.auth.models import User
from models import *
from forms import *



def mainpage(request):

	template = get_template('index.html')
	variables = Context({
		'titlehead': 'Teatre aPP',
		'pagetitle': 'Benvingut a la aplicació de Teatres',
		'contentbody': 'Aquí podràs administrar coses de Teatre',
		'user': request.user,
	})
	output = template.render(variables)
	return HttpResponse(output)


#--------------------------------------------ESCRIPTOR------------------------------------------------


class EscriptorCreate(CreateView): 
	model =  Escriptor
	#escriptor = Escriptor.objects.all()
	
	template_name = 'form.html'
	form_class = EscriptorForm
	
	def form_valid(self, form): 
		form.instance.user = self.request.user
		return super(EscriptorCreate, self).form_valid(form)




class EscriptorDetail(CreateView):

	model = Escriptor
	template_name = 'dades.html'
	
	def get_context_data(self, **kwargs):
		context = super(EscriptorDetail, self).get_context_data(**kwargs)
		return context



#----------------------------------------------ACTOR--------------------------------------------------

def actorpagina(request, format='html'):

	actor = Actor.objects.all()
	if(format=='xml'):
		template = get_template('llista.xml')
	else:
		template = get_template('llista.html')
	variables = Context({
		'pagetitle': "Llista d'actors",
		'contentbody': actor,
		'name':'/actors/',
		'tag1':'actors',
		'tag2':'actor',
		'user': request.user,
	})
	output = template.render(variables)
	return HttpResponse(output)

def actordades(request, idActor, format='html'):

	actor = Actor.objects.get(id=idActor)
	if(format=='xml'):
		template = get_template('dades.xml')
	else:
		template = get_template('dades.html')
	variables = Context({
		'pagetitle': 'Dades del actor',
		'contentbody': actor,
		'tag1':'actors',
		'tag2':'actor',
		'user': request.user,
	})
	output = template.render(variables)
	return HttpResponse(output)


#--------------------------------------------DIRECTOR------------------------------------------------

def directorpagina(request, format='html'):

	director = Director.objects.all()
	if(format=='xml'):
		template = get_template('llista.xml')
	else:
		template = get_template('llista.html')
	variables = Context({
		'pagetitle': 'Llista de Directors',
		'contentbody': director,
		'name':'/directors/',
		'tag1':'directors',
		'tag2':'director',
		'user': request.user,
	})
	output = template.render(variables)
	return HttpResponse(output)

def directordades(request, idDirector, format='html'):

	director = Director.objects.get(id=idDirector)
	if(format=='xml'):
		template = get_template('dades.xml')
	else:
		template = get_template('dades.html')
	variables = Context({
		'pagetitle': 'Dades del director',
		'contentbody': director,
		'tag1':'directors',
		'tag2':'director',
		'user': request.user,
	})
	output = template.render(variables)
	return HttpResponse(output)


#--------------------------------------------REPRESENTACIO------------------------------------------------

def representaciopagina(request, format='html'):

	representacio = Representacio.objects.all()
	if(format=='xml'):
		template = get_template('llista.xml')
	else:
		template = get_template('llista.html')
	variables = Context({
		'pagetitle': 'Llista de Representacions',
		'contentbody': representacio,
		'name':'/representacions/',
		'tag1':'representacions',
		'user': request.user,
	})
	output = template.render(variables)
	return HttpResponse(output)


def representaciodades(request, idRepresentacio, format='html'):

	representacio = Representacio.objects.get(id=idRepresentacio)
	if(format=='xml'):
		template = get_template('representacio.xml')
	else:
		template = get_template('representacio.html')
	variables = Context({
		'pagetitle': 'Informació de la representació',
		'contentbody': representacio,
		'tag1':'representacions',
		'user': request.user,
	})
	output = template.render(variables)
	return HttpResponse(output)
#-------------------------------------------------OBRA-----------------------------------------------------

def obra_Teatrepagina(request, format='html'):

	obra_Teatre = Obra_Teatre.objects.all()
	if(format=='xml'):
		template = get_template('llista.xml')
	else:
		template = get_template('llista.html')
	variables = Context({
		'pagetitle': "Llista d'obres de teatre",
		'contentbody': obra_Teatre,
		'name':'/obresTeatre/',
		'tag1':'obresTeatre',
		'user': request.user,
	})
	output = template.render(variables)
	return HttpResponse(output)


def obra_Teatredades(request, idObra, format='html'):

	obra_Teatre  = Obra_Teatre.objects.get(id=idObra)
	if(format=='xml'):
		template = get_template('Obrateatre.xml')
	else:
		template = get_template('infoObresTeatre.html')
	variables = Context({
		'pagetitle': 'Informació de les obres de teatre',
		'contentbody': obra_Teatre,
		'tag1':'obresTeatre',
		'user': request.user,
	})
	output = template.render(variables)
	return HttpResponse(output)

practica2/iTeatre/templates/dades.html
{% extends "index.html"  %}

{% block content %}
	<h1>{{person.nom}}</h1>
{% endblock %}

	{% block nextcontent %}	
		<ul>
		<p><b>Nom:</b> {{person.nom}}</p>
		<p><b>Edat:</b> {{person.edat}}</p>
		<p><b>Sexe:</b> {{person.sexe}}</p>
		<p><b>Localitat:</b> {{person.localitat}}</p>
		</ul>


<p><a href="{{ request.META.HTTP_REFERER }}">Endarrera</a></p>
<p><a href="{{request.path}}edit">Editar</a></p>
	{% endblock %}

practica2/iTeatre/templates/error.html
{% extends "index.html"  %}



		<title>Teatres de Catalunya</title>

	{% block content %}
	<h1>Error</h1>{% endblock %}{% block nextcontent %}
	<p>Tens que autentificar-te</p>
	<p><a href="/">Endarrera </a></p> 

{% endblock %}

practica2/iTeatre/templates/form.html
{% extends "index.html"  %}
{% load staticfiles %}
	{% block content %}
		<h1>Formulari</h1>
	{% endblock %}	 

	{% block nextcontent %}	
  <script>
        $(function() {
            $.getJSON("{% static "noms.json" %}", {}, function (noms) {
                $("#id_nom").autocomplete({
                    source: noms
                });
            });

            $("#id_localitat").autocomplete({
                source: function( request, response ) {
                    $.ajax({
                        url: "http://ws.geonames.org/searchJSON",
                        dataType: "jsonp",
                        data: {
                            featureClass: "P",
                            maxRows: 10,
                            name_startsWith: request.term
                        },
                        success: function( data ) {
                            response( $.map( data.geonames, function( item ) {
                                return {
                                    label: item.name + (item.adminName1 ? ", " + item.adminName1 : "") + ", " + item.countryName,
                                    value: item.name,
                                    stateOrProvince: item.adminName1,
                                    countryName: item.countryName
                                }
                            }));
                        }
                    });
                },
                minLength: 2,
                select: function( event, ui ) {
                    if (ui.item) {
                        $("#id_localitat").val(ui.item.countryName);
                    }
                }
            });
        });
    </script>
	
		
		<form method="post" action="">	
		
			{% csrf_token %}	
			<table>	
				{{ form.as_table }}	
			</table>	
			<input type="submit" value="Aceptar"/>
		</form>	
	<p><a href="{{request.META.HTTP_REFERER}}"><button>Cancel·lar</button></a></p>
{% endblock %}

practica2/iTeatre/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>

<html>
    <head>
	<link rel="stylesheet"  href=" {% static "style.css" %} " />
        <meta name="keywords" content="" />
        <meta name="description" content="" />
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<title>Teatres de Catalunya</title>
        <link href="http://fonts.googleapis.com/css?family=Arvo" rel="stylesheet" type="text/css" />
        <link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css" />
     
    </head>
    <body>
	
		<div id="bg">
			<div id="outer">
				<div id="header">
					<div id="logo">
						<h1>
							<a href="/">Teatre Catalunyans</a>
						</h1>
					</div>
					
				</div>
				<div id="main">
					<div id="sidebar">
						<h3>
							Hola! {% if user.username %}<p>User {{ user.username }}</p>
							<a href="/admin">Acc&eacute;s base de dades</a>
							{% else %} <p><a href="/login/"> Sign in </a></p>{% endif %}
						</h3>
						
						<p>
							Aqu&iacute; tens tots els links que pots llistar:
						</p>
						
						<ul class="linkedList">
							<li class="first">
								<a href="/escriptors">Escriptors</a>
							</li>
							<li>
								<a href="/actors">Actors</a>
							</li>
							<li>
								<a href="/directors">Directors</a>
							</li>
							<li>
								<a href="/representacions">Representacions</a>
							</li>
							<li class="last">
								<a href="/obresTeatre">Obres de teatre</a>
							</li>
						</ul>
					</div>
					

					<div id="content">
						<div id="box1">
						{% block content %}
							<h2><center> 
								Benvingut a  Teatre Catalunyans
							</center>
							</h2>
							<img src="{% static "images/v-de-vendetta.jpg" %}" width="800" height="500" alt="My image"/>
							{% endblock %}
						

							
							<p>{% block nextcontent %} 
								
							</p>{% endblock %}
						</div>
						
						<br class="clear" />
					</div>
					<br class="clear" />
				</div>
			</div>
			<div id="copyright">
				&copy; CatalunyaLliure | Created by Carol and Pol </a>
			</div>
		</div>
    </body>
</html>

practica2/iTeatre/templates/infoObresTeatre.html
{% extends "index.html"  %}

{% block content %}
		<h1>{{ obra_teatre }}</h1>
{% endblock %}
{% block nextcontent %}	
		<li><p> <b>{{obra_teatre.nom }}</b></p></li>
		<ol>
			<ol><p>G&egrave;nere: {{obra_teatre.Tipus}}</p>
				<p><a href="escriptors/{{obra_teatre.escriptor.id}}">Escriptor: {{obra_teatre.escriptor}}</a></p>
					<ol>{% for representacio in obra_teatre.representacions.all %}
					<li><b><p>Representacio: {{representacio.nom}}</b></p></li>
					<p>Director: {{representacio.director}}</p>
					<p>Data d'inici: {{representacio.dataInici}}</p>
					<p>Data fi: {{representacio.dataFi}}</p>
					<p>Actors: </p>
						<ol>{% for actor in representacio.actors.all  %}
						<li><p>{{actor.nom}}</p></li>
						{% endfor %}
						</ol>			
					{% endfor %}
					</ol>
			</ol>
		</ol>
<p><a href="{{request.path}}edit">Editar</a></p>
<p><a href="/obresTeatre">Endarrera</a></p>
		
{% endblock %}

practica2/iTeatre/templates/llista.html
{% extends "index.html"  %}




{% block content %}
		<h1>{{ pagetitle }}</h1>
{% endblock %}
		{% block nextcontent %}		
		<ul>
			{% for i in contentbody %}
			<li>
				<p><a href="{{name}}{{i.id}}/">{{i.nom}} </a></p>
			</li>
			{% endfor %}
		</ul>

{% endblock %}
	

practica2/iTeatre/templates/representacio.html
{% extends "index.html"  %}

{% block content %}
	<h1>{{representacio}}</h1>
{% endblock %}
 {% block nextcontent %}	
		<ol>
		<p><b>T&iacute;tol:</b> {{representacio.nom}}</p>
		<p><b>Obra que representa:</b> {{representacio.nomObra}}</p>
		<p><a href="directors/{{representacio.director.id}}"><b>Director:</b> {{representacio.director}}</a></p>
		<p><b>Comen&ccedil;a el:</b> {{representacio.dataInici}}</p>
		<p><b>Acaba el:</b> {{representacio.dataFi}}</p>
		<p><b>Actors:</b></p>
						<ol>{% for actor in representacio.actors.all  %}
						<li><p><a href="actors/{{actor.id}}">{{actor.nom}}<a/></p></li>
						{% endfor %}
						</ol>			
		</ol>
<p><a href="{{request.path}}edit">Editar</a></p>
<p><a href="/representacions">Endarrera</a></p>
{% endblock %}